import { createClientFromRequest } from 'npm:@base44/sdk@0.8.23';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

    const body = await req.json().catch(() => ({}));
    const gamesToSimulate = body.gamesToSimulate || 5_000_000;
    const TARGET_RTP_MID = 0.965;
    const TARGET_RTP_LOW = 0.95;
    const TARGET_RTP_HIGH = 0.98;

    // ── Precomputed constants ─────────────────────────────────────────────

    // Carded hands — 10 hands, win prob = 1/10
    const HAND_PAYOUTS = [2.4, 1.2, 2.4, 1.9, 1.6, 1.2, 1.6, 1.9, 1.9, 2.4]; // index 0–9

    // Rank payouts & cumulative frequency table for fast lookup
    const RANKS = ['Royal Flush','Straight Flush','Four of a Kind','Full House','Flush','Straight','Three of a Kind','Two Pair','One Pair'];
    const RANK_PAYOUTS = [null, null, 5.8, 1.5, 2.0, 2.9, 1.5, 7.4, 9.0];
    const RANK_FREQ    = [0.000154, 0.00139, 0.00168, 0.02596, 0.00327, 0.04619, 0.02113, 0.04754, 0.42257];
    // Build cumulative
    const RANK_CUM = [];
    let cum = 0;
    for (const f of RANK_FREQ) { cum += f; RANK_CUM.push(cum); }

    // Color board — 6 options (index 0-5): 3R,3B,4R,4B,5R,5B
    const COLOR_KEYS    = ['3R','3B','4R','4B','5R','5B'];
    const COLOR_PAYOUTS = [0.19, 0.19, 0.74, 0.74, 2.9, 2.9];
    // Binomial probs for 5 cards, p=0.5 for R or B
    // P(k red) = C(5,k)*0.5^5
    const p3 = 10 * 0.03125; // C(5,3)*0.5^5 = 0.3125
    const p4 = 5  * 0.03125; // 0.15625
    const p5 = 1  * 0.03125; // 0.03125
    // Colors are generated by: roll < p3 → 3R, roll < 2*p3 → 3B, etc.
    const COLOR_CUM = [p3, p3 + p3, p3 + p3 + p4, p3 + p3 + p4 + p4, p3 + p3 + p4 + p4 + p5, 1.0];

    // Strategy profiles: [handP, rankP, colorP, lhP]
    const STRATS = [
      [0.9, 0.8, 0.7, 0.6],
      [0.4, 0.3, 0.2, 0.3],
      [0.7, 0.6, 0.5, 0.8],
      [0.5, 0.5, 0.5, 0.5],
    ];
    const BET_AMOUNTS = [5, 10, 25];

    // ── Accumulators ──────────────────────────────────────────────────────
    let handBet = 0, handPayout = 0;
    let rankBet = 0, rankPayout = 0;
    let colorBet = 0, colorPayout = 0;
    let lhBet = 0, lhPayout = 0;

    // Per-rank
    const rankBets    = new Float64Array(9);
    const rankPayouts = new Float64Array(9);

    // Per-color
    const colorBets    = new Float64Array(6);
    const colorPayouts = new Float64Array(6);

    const LH_PAYOUT = 0.35;

    // ── Monte Carlo loop ──────────────────────────────────────────────────
    for (let g = 0; g < gamesToSimulate; g++) {
      // Game-level outcomes
      const winningHand = (Math.random() * 10) | 0;        // 0–9

      // Winning rank via cumulative table
      const rankRoll = Math.random();
      let gameRank = 8; // default One Pair
      for (let r = 0; r < 9; r++) { if (rankRoll < RANK_CUM[r]) { gameRank = r; break; } }

      // Color outcome
      const colorRoll = Math.random();
      let gameColor = 0;
      for (let c = 0; c < 6; c++) { if (colorRoll < COLOR_CUM[c]) { gameColor = c; break; } }

      // LH outcome
      const gameLH = Math.random() < 0.5 ? 0 : 1; // 0=LOW, 1=HIGH

      const playerCount = ((Math.random() * 5) | 0) + 1;

      for (let pl = 0; pl < playerCount; pl++) {
        const strat = STRATS[(Math.random() * 4) | 0];
        const b = BET_AMOUNTS[(Math.random() * 3) | 0];

        // Hand bet
        if (Math.random() < strat[0]) {
          const chosen = (Math.random() * 10) | 0;
          const won = chosen === winningHand;
          handBet += b;
          if (won) handPayout += b * (1 + HAND_PAYOUTS[chosen]);
        }

        // Rank bet
        if (Math.random() < strat[1]) {
          const chosen = (Math.random() * 9) | 0;
          const won = chosen === gameRank;
          const mult = RANK_PAYOUTS[chosen];
          rankBet += b;
          rankBets[chosen] += b;
          if (won && mult !== null) {
            rankPayout += b * (1 + mult);
            rankPayouts[chosen] += b * (1 + mult);
          }
        }

        // Color bet
        if (Math.random() < strat[2]) {
          const chosen = (Math.random() * 6) | 0;
          const won = chosen === gameColor;
          colorBet += b;
          colorBets[chosen] += b;
          if (won) {
            const p = b * (1 + COLOR_PAYOUTS[chosen]);
            colorPayout += p;
            colorPayouts[chosen] += p;
          }
        }

        // Low/High bet
        if (Math.random() < strat[3]) {
          const chosen = Math.random() < 0.5 ? 0 : 1;
          lhBet += b;
          if (chosen === gameLH) lhPayout += b * (1 + LH_PAYOUT);
        }
      }
    }

    // ── Calculate RTPs ────────────────────────────────────────────────────
    const totalBet    = handBet + rankBet + colorBet + lhBet;
    const totalPayout = handPayout + rankPayout + colorPayout + lhPayout;
    const overallRTP  = totalPayout / totalBet;

    const catRTPs = {
      hand:  handBet  > 0 ? handPayout  / handBet  : 0,
      rank:  rankBet  > 0 ? rankPayout  / rankBet  : 0,
      color: colorBet > 0 ? colorPayout / colorBet : 0,
      lh:    lhBet    > 0 ? lhPayout    / lhBet    : 0,
    };

    const catShares = {
      hand:  handBet  / totalBet,
      rank:  rankBet  / totalBet,
      color: colorBet / totalBet,
      lh:    lhBet    / totalBet,
    };

    // ── Derive scale factors to hit TARGET_RTP_MID ────────────────────────
    const scaleHand  = TARGET_RTP_MID / catRTPs.hand;
    const scaleRank  = TARGET_RTP_MID / catRTPs.rank;
    const scaleColor = TARGET_RTP_MID / catRTPs.color;
    const scaleLH    = TARGET_RTP_MID / catRTPs.lh;

    // Suggested payouts
    const suggestedHandPayouts = HAND_PAYOUTS.map((p, i) => ({
      id: i + 1,
      current: p,
      suggested: Math.round(p * scaleHand * 100) / 100,
    }));

    const suggestedRankPayouts = {};
    const rankDetail = {};
    for (let r = 0; r < 9; r++) {
      const mult = RANK_PAYOUTS[r];
      const rtp = rankBets[r] > 0 ? rankPayouts[r] / rankBets[r] : 0;
      suggestedRankPayouts[RANKS[r]] = mult !== null ? Math.round(mult * scaleRank * 100) / 100 : null;
      rankDetail[RANKS[r]] = {
        currentPayout: mult,
        currentRTP: (rtp * 100).toFixed(2) + '%',
        winFrequency: (RANK_FREQ[r] * 100).toFixed(4) + '%',
        suggested: mult !== null ? Math.round(mult * scaleRank * 100) / 100 : 'Progressive',
      };
    }

    const suggestedColorPayouts = {};
    const colorDetail = {};
    for (let c = 0; c < 6; c++) {
      const mult = COLOR_PAYOUTS[c];
      const rtp = colorBets[c] > 0 ? colorPayouts[c] / colorBets[c] : 0;
      const prob = (COLOR_CUM[c] - (c > 0 ? COLOR_CUM[c - 1] : 0));
      suggestedColorPayouts[COLOR_KEYS[c]] = Math.round(mult * scaleColor * 100) / 100;
      colorDetail[COLOR_KEYS[c]] = {
        currentPayout: mult,
        currentRTP: (rtp * 100).toFixed(2) + '%',
        winProbability: (prob * 100).toFixed(2) + '%',
        suggested: Math.round(mult * scaleColor * 100) / 100,
      };
    }

    const suggestedLH = Math.round(LH_PAYOUT * scaleLH * 100) / 100;

    // ── Verify theoretical RTP with suggested payouts ─────────────────────
    const theoHand  = suggestedHandPayouts.reduce((s, h) => s + (1 / 10) * (1 + h.suggested), 0) / 10;
    const theoRank  = RANKS.reduce((s, r, i) => {
      const m = suggestedRankPayouts[r];
      return s + (m !== null ? RANK_FREQ[i] * (1 + m) : 0);
    }, 0);
    const theoColor = COLOR_KEYS.reduce((s, k, i) => {
      const prob = COLOR_CUM[i] - (i > 0 ? COLOR_CUM[i - 1] : 0);
      return s + prob * (1 + suggestedColorPayouts[k]);
    }, 0);
    const theoLH    = 0.5 * (1 + suggestedLH);

    const theoOverall =
      theoHand  * catShares.hand  +
      theoRank  * catShares.rank  +
      theoColor * catShares.color +
      theoLH    * catShares.lh;

    const isCompliant = theoOverall >= TARGET_RTP_LOW && theoOverall <= TARGET_RTP_HIGH;

    return Response.json({
      success: true,
      gamesSimulated: gamesToSimulate,
      currentState: {
        overallRTP: (overallRTP * 100).toFixed(3) + '%',
        isCompliant: overallRTP >= TARGET_RTP_LOW && overallRTP <= TARGET_RTP_HIGH,
        categories: {
          hand:  { rtp: (catRTPs.hand  * 100).toFixed(2) + '%', betShare: (catShares.hand  * 100).toFixed(1) + '%' },
          rank:  { rtp: (catRTPs.rank  * 100).toFixed(2) + '%', betShare: (catShares.rank  * 100).toFixed(1) + '%' },
          color: { rtp: (catRTPs.color * 100).toFixed(2) + '%', betShare: (catShares.color * 100).toFixed(1) + '%' },
          lh:    { rtp: (catRTPs.lh    * 100).toFixed(2) + '%', betShare: (catShares.lh    * 100).toFixed(1) + '%' },
        },
      },
      suggestedPayouts: {
        hand: suggestedHandPayouts,
        rank: suggestedRankPayouts,
        color: suggestedColorPayouts,
        lowHigh: suggestedLH,
      },
      detail: {
        rankByRank: rankDetail,
        colorByColor: colorDetail,
        scalingFactors: {
          hand:  Math.round(scaleHand  * 1000) / 1000,
          rank:  Math.round(scaleRank  * 1000) / 1000,
          color: Math.round(scaleColor * 1000) / 1000,
          lh:    Math.round(scaleLH    * 1000) / 1000,
        },
      },
      verification: {
        theoreticalRTPWithSuggestedPayouts: (theoOverall * 100).toFixed(3) + '%',
        isCompliant,
        targetRange: `${TARGET_RTP_LOW * 100}% – ${TARGET_RTP_HIGH * 100}%`,
        categoryTheoretical: {
          hand:  (theoHand  * 100).toFixed(2) + '%',
          rank:  (theoRank  * 100).toFixed(2) + '%',
          color: (theoColor * 100).toFixed(2) + '%',
          lh:    (theoLH    * 100).toFixed(2) + '%',
        },
      },
    });

  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});